# +----------------------------------------------------+
# <                    Home Plugin                     >
# <                   Configuration                    >
# +----------------------------------------------------+

# Maximum number of homes (3)
maxHomes: 3

